Completed setup work
oluyaratosin123/Ruby-Capstone-Project pull request #35
Opened 2022-03-21 15:36 UTC by Lockless404

Added linters. Created item class. Setup the UI with app.rb and main.rb files.

2022-03-21 16:09 UTC, Fikerte-T requested changes
Hi @Lockless404 , 

Good job setting up the UI and implementing the methods.  
However, there are some issues that you still need to work on to go to the next milestone. 

## Required Changes ♻️


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2022-03-21 16:09 UTC, Fikerte-T commented on app.rb
> +      break if option == '13'
[] Input is an undefined variable. I think it should be `get.chomp`  and receive input from the user

2022-03-21 16:09 UTC, Fikerte-T commented on item.rb
> +  end
-  Here the difference will be a negative integer. You can switch the operands to make the result positive.

 [ ] optional the year difference can be calculated and returned in one line
date.year - @publish_date.year > 10

2022-03-21 16:16 UTC, Fikerte-T approved these changes
Hi 👋 @Lockless404 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-03-21 22:52 UTC, oluyaratosin123 commented
Hello @Lockless404 ,
I know your project has been approved but as a code checker I later examined that the app wasn't running properly, the column below shows the error
![apprb](https://user-images.githubusercontent.com/83566118/159375500-1de33424-c3ad-4ee2-b9c7-26a1bda6badd.PNG)

- [ ] Please go back to your `app.rb` file  **line-6** apply 
```Ruby 
option = gets.chomp.to_i 
```

2022-03-21 22:55 UTC, oluyaratosin123 requested changes

2022-03-21 22:55 UTC, oluyaratosin123 commented on app.rb
> +      option = get.chomp
Hello @Lockless404 ,
I know your project has been approved but as a code checker I later examined that the app wasn't running properly, the column below shows the error

![apprb](https://user-images.githubusercontent.com/83566118/159375500-1de33424-c3ad-4ee2-b9c7-26a1bda6badd.PNG)

- [ ] Please go back to your `app.rb` file  **line-6** apply 
```Ruby 
option = gets.chomp.to_i 
```
Cheers and Happy coding!👏👏👏

2022-03-21 22:57 UTC, oluyaratosin123 approved these changes

2022-03-22 08:54 UTC, Fikerte-T approved these changes
Hi 👋 Edward, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

2022-03-22 08:54 UTC, merged